# Generated by Django 5.1.4 on 2025-01-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='es_diferida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha_diferida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
